name: Dispatch NPM release

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'Package to release'
        required: true
        options:
          - core
          - credentials
          - wallet
      level:
        type: choice
        description: Select the release update level
        options:
          - prerelease
          - prepatch
          - patch
          - preminor
          - minor
          - premajor
          - major
      preid:
        type: choice
        description: Select pre-id (alpha | beta)
        options:
          - alpha
          - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 🔧 Git
        run: |
          git config user.email "github@indentitylabs.ooo"
          git config user.name "Github InternetIdentityLabs"
      - name: 🔧 Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: 🔧 Yarn
        run: |
          yarn config set version-git-message "chore(${{ github.event.inputs.package }}): release v%s"
          yarn config set version-tag-prefix "@nfid/${{ github.event.inputs.package }}@"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🤖 Install
        run: yarn

      - name: 🤖 Increment package version
        working-directory: packages/${{ github.event.inputs.package }}
        run: |
          if [[ ${{ github.event.inputs.level }} == "pre"* ]]; then
            yarn version --${{ github.event.inputs.level }} --preid ${{ github.event.inputs.preid }}
          else
            yarn version --${{ github.event.inputs.level }}
          fi

      - name: 📦 Build and publish package on NPM
        run: npx nx publish ${{ github.event.inputs.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🎉 Push tags
        run: |
          git push
          git push --tags
