name: Trigger Playground Tests

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Pause for 15 seconds for canceling
        run: |
          sleep 15

      - name: Triggering Playground tests
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: internet-identity-labs
          repo: nfid-frontend
          workflow_file_name: sdk-test.yml
          github_token: ${{ secrets.TRIGGER_SDK_PLAYGROUND_PAT }}
          comment_downstream_url: ${{ github.event.head_commit.message }}