name: Test
on:
  push:
    branches:
      - '**'
jobs:
  test:
    permissions:
      contents: 'read'
      actions: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Print NX ENV Variables
        run: |
          echo "NX_BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - run: npx nx affected:test
